### ISSUE TITLE
setup内でダミー変数へ代入しないと、MQTTの接続に失敗する

### ISSUE THREAD

**Issue by kiyopikko** [milk-cocoa/arduino#1]
以下のように、グローバルでダミーの変数（変数名は自由）を宣言して、setup内でその変数に代入をしないと、MQTTの接続で「3 Server Unavailavle」で失敗します。
https://github.com/kiyopikko/m0_pro_milkcocoa/blob/master/fail1.ino

M0 pro、M0両方で同じ問題が起こります。ESP-WROOM-02のファームウェアは購入してから書き換えていません。
参考：https://teratail.com/questions/27633

**Comment by exshonda** [comment]
確認させて下さい．

IDE 1.7.8 のM0のライブラリにはバグがあります．以下の変更を適用して試してもらえますででしょうか．

./hardware/arduino/samd/cores/arduino/USB/samd21_device.c : 152行目 メモリリーク

```
for (i = 0; i < sizeof(usb_endpoint_table)/4; i++) {
    (*(uint32_t *)((uint32_t *)(&usb_endpoint_table[0])+i)) = 0;
}
```

**Comment by kiyopikko** [comment]
適用したところ、接続に成功しました。

**Comment by exshonda** [comment]
こちらの問題も直りましたでしょうか．

https://github.com/milk-cocoa/Milkcocoa_Arduino_SDK/issues/2

**Comment by kiyopikko** [comment]
#2 は依然として過去のpush内容がとれるときがあります。

気づいた点として、
正常にpush内容がとれるときはすぐにコールバックが呼ばれますが、
過去のpush内容がとれるときは、3秒〜5秒くらい待ってコールバックが呼ばれます。

**Comment by exshonda** [comment]
README.mdにパッチの説明を加えました．このISSUEはクローズします．
https://github.com/milk-cocoa/Milkcocoa_Arduino_SDK/commit/871b34559a51e37bff186b47638b537c4cfce7ee
