### ISSUE TITLE
Genuino101でのコンパイルエラーについて

### ISSUE THREAD

**Issue by genumen** [milk-cocoa/arduino#4]
Genuino101(Arduino101)とESP8266を通信させて動かしているのですがプログラムをコンパイルするときに以下の様なエラーが出てきてしまいます。

 エラー:
Milkcocoa_Arduino_SDK-master/Adafruit_MQTT.cpp:28:25: fatal error: avr/dtostrf.h: No such file or directory
 #include "avr/dtostrf.h"
                                     ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino 101.

どのようにしたら解決出来ますか？

**Comment by exshonda** [comment]
#include "avr/dtostrf.h" を外してコンパイルして，エラーとなる関数を定義しているGenuino101のファイルをインクルードするとどうでしょうか．

**Comment by genumen** [comment]
#include "avr/dtostrf.h"をコメントアウトしたら正常に動くようになりました.
